# Generated by Django 4.1.5 on 2023-04-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0006_remove_order_shipping_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
