# Generated by Django 4.1.5 on 2023-04-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0009_product_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDISBestSeller',
            field=models.BooleanField(default=False, verbose_name='Best Seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISNew',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
    ]
