# Generated by Django 4.1.5 on 2023-04-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0012_rename_prdiproduct_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image4'),
        ),
    ]
