# Generated by Django 4.1.5 on 2023-04-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0015_rename_discountprice_product_discountprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mainimage',
            new_name='MainImage',
        ),
    ]
