# Generated by Django 4.1.5 on 2023-04-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0016_rename_mainimage_product_mainimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDISBestSeller',
            new_name='bestseller',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDISNew',
            new_name='new',
        ),
    ]
