# Generated by Django 4.1.5 on 2023-04-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0018_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountprice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Discount Price'),
        ),
    ]
