# Generated by Django 4.1.5 on 2023-04-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0019_alter_product_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
    ]
